FINANCIALS_DEFAULT_SCHEMA = {
    "category": "Portfolio_Performance",
    "fields": [
        {"key": "reporting_period", "label": "Reporting Period", "type": "text", "required": True},
        {
            "key": "interest_income",
            "label": "Interest Income (lakhs)",
            "type": "currency_lakhs",
            "required": True,
        },
        {"key": "fee_commission_income", "label": "Fees & Commission Income (lakhs)", "type": "currency_lakhs"},
        {
            "key": "total_revenue_operations",
            "label": "Total Revenue from Operations (lakhs)",
            "type": "currency_lakhs",
            "required": True,
        },
        {"key": "total_income", "label": "Total Income (lakhs)", "type": "currency_lakhs", "required": True},
        {"key": "finance_costs", "label": "Finance Costs (lakhs)", "type": "currency_lakhs"},
        {"key": "employee_benefits", "label": "Employee Benefits (lakhs)", "type": "currency_lakhs"},
        {
            "key": "impairment_expense",
            "label": "Impairment on Financial Instruments (lakhs)",
            "type": "currency_lakhs",
        },
        {"key": "total_expenses", "label": "Total Expenses (lakhs)", "type": "currency_lakhs"},
        {
            "key": "profit_before_tax",
            "label": "Profit Before Tax (lakhs)",
            "type": "currency_lakhs",
            "required": True,
        },
        {
            "key": "profit_after_tax",
            "label": "Profit After Tax (lakhs)",
            "type": "currency_lakhs",
            "required": True,
        },
        {"key": "eps_basic", "label": "EPS Basic (Rs.)", "type": "number"},
        {"key": "eps_diluted", "label": "EPS Diluted (Rs.)", "type": "number"},
        {"key": "debt_equity_ratio", "label": "Debt-Equity Ratio", "type": "number"},
        {"key": "net_worth_lakhs", "label": "Net Worth (lakhs)", "type": "currency_lakhs"},
        {"key": "net_profit_margin", "label": "Net Profit Margin (%)", "type": "percentage"},
        {"key": "gnpa_percent", "label": "Gross NPA (%)", "type": "percentage"},
        {"key": "nnpa_percent", "label": "Net NPA (%)", "type": "percentage"},
        {"key": "provision_coverage_ratio", "label": "Provision Coverage Ratio (%)", "type": "percentage"},
        {"key": "crar_percent", "label": "Capital Risk Adequacy Ratio (%)", "type": "percentage"},
        {"key": "lcr_percent", "label": "Liquidity Coverage Ratio (%)", "type": "percentage"},
        {"key": "total_debts_to_total_assets", "label": "Total Debts to Total Assets", "type": "number"},
        {"key": "loan_assignment_count", "label": "Loans Assigned (count)", "type": "number"},
        {
            "key": "loan_assignment_amount_lakhs",
            "label": "Loans Assigned (amount, lakhs)",
            "type": "currency_lakhs",
        },
        {"key": "co_lending_count", "label": "Co-Lending Loans (count)", "type": "number"},
        {"key": "co_lending_amount_lakhs", "label": "Co-Lending Amount (lakhs)", "type": "currency_lakhs"},
    ],
}

